-- =====================================================
-- web_funnel_plans — ADD client_plan_key (idempotency)
-- Created: 2026-09-16
--
-- Canonical owner of funnel schema: this repo (app/backend).
-- The funnel web repo must NOT ship its own schema migrations.
--
-- Purpose:
--   * client_plan_key  uuid  UNIQUE  NOT NULL
--     Stable idempotency key generated by the funnel WEB once per funnel and
--     reused on retry (create-funnel-plan). On retry with the same key and a
--     pending plan, the web reuses the row and re-emits a NEW claim token
--     (replacing claim_token_hash); if the plan is no longer pending (or
--     expired), the web returns 409 and does NOT create a duplicate.
--
-- Integrates with the current canonical contract (UNCHANGED):
--   claim_token_hash  text UNIQUE NOT NULL (SHA-256, raw token NEVER stored)
--   claimed_by_user_id uuid NULL      (owner, assigned on pending -> claiming)
--   status text NOT NULL CHECK pending|claiming|claimed|expired
--   expires_at        timestamptz    (canonical; NOT claim_expires_at)
--   claimed_at        timestamptz
--
-- Constraints / compatibility:
--   * legacy table `funnel_plans` is NOT touched.
--   * table name `web_funnel_plans` is NOT renamed.
--   * columns named `claim_expires_at` / `claim_token` are NOT created here:
--     the canonical contract uses `expires_at` / `claim_token_hash`.
-- =====================================================

-- ── 1) New column (nullable until backfill) ────────────────────────────────
ALTER TABLE public.web_funnel_plans
  ADD COLUMN IF NOT EXISTS client_plan_key UUID;

-- ── 2) Backfill pre-existing rows with a fresh random key ──────────────────
UPDATE public.web_funnel_plans
   SET client_plan_key = gen_random_uuid()
 WHERE client_plan_key IS NULL;

-- ── 3) NOT NULL once every row has a key ──────────────────────────────────
ALTER TABLE public.web_funnel_plans
  ALTER COLUMN client_plan_key SET NOT NULL;

-- ── 4) UNIQUE -- idempotency key (first come, first served) ───────────────
DROP INDEX IF EXISTS public.web_funnel_plans_client_plan_key_uq;
CREATE UNIQUE INDEX web_funnel_plans_client_plan_key_uq
  ON public.web_funnel_plans (client_plan_key);

-- ── 5) Comment ────────────────────────────────────────────────────────────
COMMENT ON COLUMN public.web_funnel_plans.client_plan_key IS
  'Stable funnel idempotency key (WEB-generated, one per funnel, reused on retry). UNIQUE to guarantee create-funnel-plan retries never duplicate plans.';